In [1]:
import numpy as np

In [7]:
zeros = np.zeros((3,3))


print(zeros)

ones = np.ones((4,4))

print()

print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Identity Matrix


the_eye = np.eye(5)

print(the_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
one_dimension_matrix = np.random.rand(5) # Returns numbers from 0 to 1
print(one_dimension_matrix)

[0.79121365 0.07113552 0.40764907 0.20214904 0.8588229 ]


In [15]:
two_dimension_matrix = np.random.rand(5,5) # Returns numbers from 0 to 1 in two dimensions
print(two_dimension_matrix)

[[0.97217645 0.7750764  0.80411129 0.9710598  0.02389055]
 [0.27123225 0.09870749 0.75675137 0.85318394 0.4694614 ]
 [0.48044068 0.64267427 0.16919616 0.3110228  0.69469137]
 [0.19756885 0.76486973 0.90172318 0.53336796 0.24791541]
 [0.37964538 0.32103683 0.87037401 0.31319767 0.42317329]]


In [18]:
random_ints = np.random.randint(1,100,10) # Returns 10 numbers from 0 to 100 excluding 100
print(random_ints)
print(type(random_ints))

[34 73 27 78 61 34 53 35 55 21]
<class 'numpy.ndarray'>


In [21]:
#Reshape method turns one dimensional array in n dimensions

#Before Reshape

arr = np.arange(25)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [28]:
#After Reshape

reshaped_arr = arr.reshape(5,5) # NB! For reshaping the values should produce the same number of elements as the original array has(5 x 5 = 25), but (5 x 10) will throw exception

print(reshaped_arr)
print(reshaped_arr[2,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
13


In [ ]:
print(arr.max()) # max value

print(arr.min()) # min value

print(arr.argmin()) # min value index

print(arr.argmax()) # max value index

24
0
0
24
