In [7]:
import sympy as sym
import numpy as np


from math import gcd

In [12]:
#Create a matrix that contains 10 rows and 15 columns, where each element is equial to 99

matrix  = np.full((10, 15), 99)


#Populate the matrix such that the i-th row and j-th column contains gcd(i+1,j+1)

rows, cols = 10, 15

for i in range(rows):
    for j in range(cols):
        matrix[i][j] = gcd(i + 1, j + 1)


print(matrix)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  1  2  1  2  1  2  1  2  1  2  1  2  1]
 [ 1  1  3  1  1  3  1  1  3  1  1  3  1  1  3]
 [ 1  2  1  4  1  2  1  4  1  2  1  4  1  2  1]
 [ 1  1  1  1  5  1  1  1  1  5  1  1  1  1  5]
 [ 1  2  3  2  1  6  1  2  3  2  1  6  1  2  3]
 [ 1  1  1  1  1  1  7  1  1  1  1  1  1  7  1]
 [ 1  2  1  4  1  2  1  8  1  2  1  4  1  2  1]
 [ 1  1  3  1  1  3  1  1  9  1  1  3  1  1  3]
 [ 1  2  1  2  5  2  1  2  1 10  1  2  1  2  5]]
